apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: paulbamberg22/platformservice:latest
        env:
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: platformsdb-conn-cm
              key: "kube-system.platformsdb-host"
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: platformsdb-conn-cm
              key: kube-system.platformsdb-port
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: platformsdb-conn-cm
              key: kube-system.platformsdb-user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: platformsdb-password
              key: password
        - name: ConnectionStrings__PlatformsConnectionString
          value: Host=$(PGHOST);Port=$(PGPORT);Database=platformsdb;Username=$(PGUSER);Password=$(PGPASSWORD);
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: platformgrpc
    protocol: TCP
    port: 666
    targetPort: 666
