apiVersion: v1
kind: ConfigMap
metadata:
  name: platformsdb-conn-cm
data: {}
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: platformsdb-host
spec:
  to:
    name: platformsdb-conn-cm
    kind: configmap
  from:
    path: ".status.endpoint.address"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: platformsdb
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: platformsdb-port
spec:
  to:
    name: platformsdb-conn-cm
    kind: configmap
  from:
    path: ".status.endpoint.port"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: platformsdb
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: platformsdb-user
spec:
  to:
    name: platformsdb-conn-cm
    kind: configmap
  from:
    path: ".spec.masterUsername"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: platformsdb
